name: GitHub-Profile-3D-Contrib

on:
  schedule: 
    - cron: "*/5 * * * *" # Runs daily at 18:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile 3D Contrib
    steps:
      - name: Set Up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Run 3D Contrib Action
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Generated 3D Contribution Calendar" || echo "No changes to commit"
          git push
